from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class CptMetadataPort(Protocol):
    """Port for CPT display metadata — satisfied by legacy and hybrid loaders."""

    def get(self, cpt_code: str) -> dict[str, Any] | None: ...

    def is_timed(self, cpt_code: str) -> bool: ...

    def get_display_name(self, cpt_code: str) -> str: ...


@runtime_checkable
class CptAocPort(Protocol):
    """Port for CPT Add-On Code relationships."""
    def is_addon_code(self, cpt_code: str) -> bool: ...
    def get_parent_code(self, cpt_code: str) -> str | None: ...
    def get_allowed_addons(self, cpt_code: str) -> list[str]: ...


@runtime_checkable
class CptGeneralInfoPort(Protocol):
    """Port for CPT general information and billing rules."""
    def get_description(self, cpt_code: str) -> str | None: ...
    def get_billing_rule(self, cpt_code: str) -> str | None: ...


@runtime_checkable
class CptIcd10Port(Protocol):
    """Port for CPT to ICD-10 cross-compatibility checks."""
    def get_valid_icd10_codes(self, cpt_code: str) -> list[str]: ...
    def is_valid_icd10(self, cpt_code: str, icd10_code: str) -> bool: ...


@runtime_checkable
class CptMuePort(Protocol):
    """Port for CPT Medically Unlikely Edits (MUE) limits."""
    def get_mue_value(self, cpt_code: str) -> int | None: ...
    def get_mue_adjudication_indicator(self, cpt_code: str) -> int | None: ...
    def get_mue_rationale(self, cpt_code: str) -> str | None: ...
    def get_mue_adjudication_level(self, cpt_code: str) -> str | None: ...


@runtime_checkable
class CptPtpPort(Protocol):
    """Port for CPT Procedure-to-Procedure (PTP / NCCI) bundle edits."""
    def get_bundled_into(self, cpt_code: str) -> list[dict[str, str]]: ...
    def get_bundles_others(self, cpt_code: str) -> list[dict[str, str]]: ...
    def is_bundled_into(self, cpt_code: str, primary_cpt: str) -> bool: ...
    def bundles_code(self, cpt_code: str, secondary_cpt: str) -> bool: ...
    def get_modifier_indicator(self, cpt_code: str, related_cpt: str) -> str | None: ...

    def check_conflict(self, cpt_a: str, cpt_b: str) -> dict[str, Any] | None:
        """
        Check for a PTP/NCCI conflict between two CPT codes.

        Returns a dict with keys matching the NcciRule shape if a conflict exists:
        {
            "cpt_a": str,
            "cpt_b": str,
            "payable_code": str,      # column-1 (payable)
            "bundled_code": str,       # column-2 (bundled)
            "conflict_type": str,      # e.g. "ptp_bundle"
            "body_region_sensitive": bool,
            "modifier_59_possible": bool,
            "explanation": str,
        }
        Returns None if no conflict exists.
        """

@runtime_checkable
class BillingCategoryPort(Protocol):
    """Port for PT/OT/SLP specific billing category constraints."""
    def get_category_id(self, cpt_code: str) -> str | None: ...
    def get_billing_rule(self, cpt_code: str) -> str | None: ...
    def get_description(self, cpt_code: str) -> str | None: ...
    def get_segment_size_minutes(self, cpt_code: str) -> int | None: ...
    def get_unit_threshold_minutes(self, cpt_code: str) -> int | None: ...
    def get_min_time_for_1_unit(self, cpt_code: str) -> str | None: ...
    def get_max_units_allowed(self, cpt_code: str) -> str | None: ...
    def get_time_band(self, cpt_code: str) -> str | None: ...
